In [1]:
import netCDF4 as nc
import numpy as np

Grab a netcdf file near the center of the domain (remember that the ICs are for a column located at x = i and y = j where the naming convention is `ics_i_j.nc`)

In [5]:
path = '/data/keeling/a/jcurtis2/c/wrf_partmc_new_repo/wrf_partmc/boundary_and_initial_conditions/ics/ics_new_001_001.nc'
data = nc.Dataset(path)

In [22]:
data

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    dimensions(sizes): n_aero_modes(3), n_aero_specs(20), nz(39)
    variables(dimensions): int32 mode_type(n_aero_modes, nz), float64 char_radius(n_aero_modes, nz), float64 log10_std_dev_radius(n_aero_modes, nz), float64 num_conc(n_aero_modes, nz), float64 vol_frac(n_aero_specs, n_aero_modes, nz), float64 vol_frac_std(n_aero_specs, n_aero_modes, nz), int32 source(n_aero_modes, nz)
    groups: 

In [9]:
[variable for variable in data.variables.keys()]

['mode_type',
 'char_radius',
 'log10_std_dev_radius',
 'num_conc',
 'vol_frac',
 'vol_frac_std',
 'source']

The CARES domain has dimensions 170x160x40 (x, y, z).

In [109]:
data['source'][:]

masked_array(
  data=[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
         3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]],
  mask=False,
  fill_value=999999,
  dtype=int32)

In [30]:
aero_species_list = ['SO4','NO3','Cl','NH4','MSA','ARO1','ARO2','ALK1','OLE1','API1',
                'API2','LIM1','LIM2','CO3','Na','Ca','OIN','OC','BC','H2O']  

In [31]:
urban_plume_aero_ics = {'aitken_mode': {'number_conc [m^-3]': 3.2e9,
                                        'geom_mean_diam [m]': 0.2e-6,
                                        'geom_std_dev': 1.45,
                                        'mass_frac': {'SO4': 0.3636,'NO3': 0,
                                                      'Cl': 0,'NH4': 0.1364,
                                                      'MSA': 0,'ARO1': 0,
                                                      'ARO2': 0, 'ALK1': 0,
                                                      'OLE1': 0,'API1': 0,
                                                      'API2': 0,'LIM1': 0,
                                                      'LIM2': 0,'CO3': 0,
                                                      'Na': 0,'Ca': 0,
                                                      'OIN': 0,'OC': 0.5,
                                                      'BC': 0,'H2O': 0}
                                         },
                        'accum_mode': {'number_conc [m^-3]': 2.9e9,
                                        'geom_mean_diam [m]': 0.116e-6,
                                        'geom_std_dev': 1.65,
                                        'mass_frac': {'SO4': 0.3636,'NO3': 0,
                                                      'Cl': 0,'NH4': 0.1364,
                                                      'MSA': 0,'ARO1': 0,
                                                      'ARO2': 0, 'ALK1': 0,
                                                      'OLE1': 0,'API1': 0,
                                                      'API2': 0,'LIM1': 0,
                                                      'LIM2': 0,'CO3': 0,
                                                      'Na': 0,'Ca': 0,
                                                      'OIN': 0,'OC': 0.5,
                                                      'BC': 0,'H2O': 0}
                                         },
                        }

netcdf ics_new_001_001 {
dimensions:
        n_aero_modes = 3 ;
        n_aero_specs = 20 ;
        nz = 39 ;
variables:
        int mode_type(n_aero_modes, nz) ;
        double char_radius(n_aero_modes, nz) ;
        double log10_std_dev_radius(n_aero_modes, nz) ;
        double num_conc(n_aero_modes, nz) ;
        double vol_frac(n_aero_specs, n_aero_modes, nz) ;
        double vol_frac_std(n_aero_specs, n_aero_modes, nz) ;
        int source(n_aero_modes, nz) ;
}

In [101]:
mass_frac_array = np.zeros((n_aero_modes, n_aero_specs))
for i, (mode, attributes) in enumerate(urban_plume_aero_ics.items()):
    mass_fracs = attributes['mass_frac'] # could convert to list
    mass_frac_list = list(mass_fracs.values())
    mass_frac_array[i, :] = np.array(mass_frac_list)
#mass_frac_array = np.repeat(mass_frac_array.reshape(n_aero_modes,n_aero_specs), repeats=n_levels, axis=1)


In [102]:
mass_frac_array

array([[0.3636, 0.    , 0.    , 0.1364, 0.    , 0.    , 0.    , 0.    ,
        0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
        0.    , 0.5   , 0.    , 0.    ],
       [0.3636, 0.    , 0.    , 0.1364, 0.    , 0.    , 0.    , 0.    ,
        0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    , 0.    ,
        0.    , 0.5   , 0.    , 0.    ]])

In [133]:
mass_frac_array = np.zeros((n_aero_specs, n_aero_modes))
for i, (mode, attributes) in enumerate(urban_plume_aero_ics.items()):
    mass_fracs = attributes['mass_frac'] # could convert to list
    mass_frac_list = list(mass_fracs.values())
    mass_frac_array[:, i] = np.array(mass_frac_list)
vol_frac_array = np.zeros((n_aero_specs, n_aero_modes, n_levels))
for i in range(n_levels):
    vol_frac_array[:, :, i] = mass_frac_array
vol_frac[:] = vol_frac_array

In [137]:
vol_frac[:] = vol_frac_array

ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (2, 20, 40) and arg 1 with shape (20, 2, 40).

In [127]:
mass_frac_array

array([[0.3636, 0.3636],
       [0.    , 0.    ],
       [0.    , 0.    ],
       [0.1364, 0.1364],
       [0.    , 0.    ],
       [0.    , 0.    ],
       [0.    , 0.    ],
       [0.    , 0.    ],
       [0.    , 0.    ],
       [0.    , 0.    ],
       [0.    , 0.    ],
       [0.    , 0.    ],
       [0.    , 0.    ],
       [0.    , 0.    ],
       [0.    , 0.    ],
       [0.    , 0.    ],
       [0.    , 0.    ],
       [0.5   , 0.5   ],
       [0.    , 0.    ],
       [0.    , 0.    ]])

In [107]:
test.shape

(2, 20, 40)

In [92]:
test = np.resize(mass_frac_array, (2, 20, 30))

In [108]:
np.repeat(np.arange(1, 3, 1).reshape(n_aero_modes,1), repeats=n_levels, axis=1)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]])

In [138]:
file_path = '/data/keeling/a/sf20/b/wrf-partmc-spatial-het/WRFV3/test/em_les/notebooks/test.nc'
ncfile = nc.Dataset(file_path, 'w')

n_levels = 40
n_aero_modes = 2
n_aero_specs = 20

#i_level = str(i + 1).zfill(3)
#grp = ncfile.createGroup(f'level_{i_level}')

modes_dim = ncfile.createDimension('n_aero_modes', n_aero_modes)
aero_specs_dim = ncfile.createDimension('n_aero_specs', n_aero_specs)
z_dim = ncfile.createDimension('nz', n_levels)

# TODO: not sure what this is for...Jeff has this set to 1 for all modes, levels
mode_type = ncfile.createVariable('mode_type', 'f8', ('n_aero_modes', 'nz'))
mode_type[:] = 1

# float64 char_radius(n_modes)
char_radius = ncfile.createVariable('char_radius', 'f8', ('n_aero_modes', 'nz'))
char_radius.unit = 'm'
char_radius.long_name = "characteristic_radius"
char_radius.standard_name = "characteristic_radius"
char_radius.description = "Characteristic radius, with meaning dependent on mode type"
char_radii = []
for mode, attributes in urban_plume_aero_ics.items():
    geom_mean_diam = attributes['geom_mean_diam [m]']
    geom_mean_radius = 0.5*geom_mean_diam
    char_radii.append(geom_mean_radius)
char_radii = np.repeat(np.array(char_radii).reshape(n_aero_modes,1), repeats=n_levels, axis=1)
char_radius[:, :] = char_radii

# float64 log10_std_dev_radius(n_modes)
log10_std_dev_radius = ncfile.createVariable('log10_std_dev_radius', 'f8', ('n_aero_modes', 'nz'))
log10_std_dev_radius.unit = 'm'
log10_std_dev_radius.long_name = "log10_std_dev_radius"
log10_std_dev_radius.standard_name = "log10_std_dev_radius"
log10_std_dev_radius.description = "Log base 10 of geometric standard deviation of radius, (m)."
log10_std_dev_radii = []
for mode, attributes in urban_plume_aero_ics.items():
    std_dev = attributes['geom_std_dev']
    log10_std_dev = np.log10(std_dev)
    log10_std_dev_radii.append(log10_std_dev)
log10_std_dev_radii = np.repeat(np.array(log10_std_dev_radii).reshape(n_aero_modes,1), repeats=n_levels, axis=1)
log10_std_dev_radius[:] = log10_std_dev_radii

# float64 num_conc(n_modes)
num_conc = ncfile.createVariable('num_conc', 'f8', ('n_aero_modes', 'nz'))
num_conc.unit = '# m^{-3}'
num_conc.long_name = "total number concentration"
num_conc.standard_name = "total number concentration"
num_conc.description = "Total number concentration of mode (#/m^3)."
num_concentrations = []
for mode, attributes in urban_plume_aero_ics.items():
    num_concentration = attributes['number_conc [m^-3]']
    num_concentrations.append(num_concentration)
num_concentrations = np.repeat(np.array(num_concentrations).reshape(n_aero_modes,1), repeats=n_levels, axis=1)
num_conc[:] = num_concentrations

# float64 vol_frac(n_modes, n_aero_specs)
vol_frac = ncfile.createVariable('vol_frac', 'f8', ('n_aero_specs', 'n_aero_modes', 'nz'))
vol_frac.unit = '(1)'
vol_frac.long_name = "species fractions"
vol_frac.standard_name = "species_fractions"
vol_frac.description = "Species fractions by volume [length \c aero_data%%n_spec]."
mass_frac_array = np.zeros((n_aero_specs, n_aero_modes))
for i, (mode, attributes) in enumerate(urban_plume_aero_ics.items()):
    mass_fracs = attributes['mass_frac'] # could convert to list
    mass_frac_list = list(mass_fracs.values())
    mass_frac_array[:, i] = np.array(mass_frac_list)
vol_frac_array = np.zeros((n_aero_specs, n_aero_modes, n_levels))
for i in range(n_levels):
    vol_frac_array[:, :, i] = mass_frac_array
vol_frac[:] = vol_frac_array

vol_frac_std = ncfile.createVariable('vol_frac_std', 'f8', ('n_aero_specs', 'n_aero_modes', 'nz'))
vol_frac_std.unit = '(1)'
vol_frac_std.long_name = "species fractions"
vol_frac_std.standard_name = "species_fractions"
vol_frac_std.description = "Species fractions by volume [length \c aero_data%%n_spec]."
#mass_frac_array = np.zeros((n_aero_modes, n_aero_specs))
#for i, (mode, attributes) in enumerate(urban_plume_aero_ics.items()):
#    mass_fracs = attributes['mass_frac'] # could convert to list
#    mass_frac_list = list(mass_fracs.values())
#    mass_frac_array[i, :] = np.array(mass_frac_list)
vol_frac_std[:] = 0 # Jeff seems to have all of these set to zero

# int32 source(n_modes) 
# NOTE: this is source_id in the emission files
source = ncfile.createVariable('source', 'i', ('n_aero_modes', 'nz'))
source.unit = '(1)'
source.long_name = "Source number."
source.standard_name = "Source number"
source.description = "Source number."
sources = np.repeat(np.arange(1, 3, 1).reshape(n_aero_modes,1), repeats=n_levels, axis=1)
source[:] = sources





In [139]:
ncfile_data = nc.Dataset('test.nc')

In [140]:
ncfile

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    dimensions(sizes): n_aero_modes(2), n_aero_specs(20), nz(40)
    variables(dimensions): float64 mode_type(n_aero_modes, nz), float64 char_radius(n_aero_modes, nz), float64 log10_std_dev_radius(n_aero_modes, nz), float64 num_conc(n_aero_modes, nz), float64 vol_frac(n_aero_specs, n_aero_modes, nz), float64 vol_frac_std(n_aero_specs, n_aero_modes, nz), int32 source(n_aero_modes, nz)
    groups: 

In [114]:
ncfile['mode_type'][:]

masked_array(
  data=[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1., 1.]],
  mask=False,
  fill_value=1e+20)

In [116]:
for variable in ncfile.variables.keys():
    print(variable)
    print('----------------------------')
    print('Mine')
    print(ncfile[variable][:])
    print('')
    print('Jeff')
    print(data[variable][:])
    print('')

mode_type
----------------------------
Mine
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Jeff
[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
  1 1 1]]

char_radius
----------------------------
Mine
[[1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07
  1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07
  1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07
  1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07 1.0e-07
  1.0e-07 1.0e-07 1.0e-07 1.0e-07]
 [5.8e-08 5.8e-08 5.8e-08 5.8e-08 5.8e-08 5.8e-08 5.8e-08 5.8e-08 5.8e-

In [141]:
for variable in ncfile.variables.keys():
    print(variable)
    print('----------------------------')
    print('Mine')
    print(ncfile[variable][:].shape)
    print('')
    print('Jeff')
    print(data[variable][:].shape)
    print('')

mode_type
----------------------------
Mine
(2, 40)

Jeff
(3, 39)

char_radius
----------------------------
Mine
(2, 40)

Jeff
(3, 39)

log10_std_dev_radius
----------------------------
Mine
(2, 40)

Jeff
(3, 39)

num_conc
----------------------------
Mine
(2, 40)

Jeff
(3, 39)

vol_frac
----------------------------
Mine
(20, 2, 40)

Jeff
(20, 3, 39)

vol_frac_std
----------------------------
Mine
(20, 2, 40)

Jeff
(20, 3, 39)

source
----------------------------
Mine
(2, 40)

Jeff
(3, 39)

