In [7]:
import pandas as pd
import numpy as np

In [11]:
aero_props = pd.read_csv('/data/keeling/a/sf20/b/wrf_partmc/WRFV3/test/em_les/urban_plume_aero_emiss.csv')

In [3]:
aero_props

mode_name   mode_type     num_conc  geom_mean_diam  log10_geom_std_dev  \
0   cooking  log_normal    9000000.0    8.640000e-08                0.28   
1    diesel  log_normal  160000000.0    5.000000e-08                0.24   
2  gasoline  log_normal   50000000.0    5.000000e-08                0.24   

   mass_frac_OC  mass_frac_BC  
0           1.0           NaN  
1           0.3           0.7  
2           0.8           0.2

In [13]:
np.array(1+aero_props.index)

array([1, 2, 3])

In [21]:
n_times = 25
n_modes =3
n_aero_specs = 20
num_conc = np.zeros((n_times, n_modes))

In [18]:
aero_props.num_conc

0      9000000.0
1    160000000.0
2     50000000.0
Name: num_conc, dtype: float64

In [19]:
num_conc[:] = aero_props.num_conc

In [20]:
num_conc

array([[9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07],
       [9.0e+06, 1.6e+08, 5.0e+07]])

In [22]:
vol_frac = np.zeros((n_times, n_modes, n_aero_specs))

In [46]:
OC_idx = 17
BC_idx = 18
cooking_mode_idx = 0
diesel_mode_idx = 1
gas_mode_idx = 2

vol_frac[:, cooking_mode_idx, OC_idx] = 1

vol_frac[:, diesel_mode_idx, OC_idx] = .3
vol_frac[:, diesel_mode_idx, BC_idx] = .7

vol_frac[:, gas_mode_idx, OC_idx] = .8
vol_frac[:, gas_mode_idx, BC_idx] = .2

In [47]:
vol_frac

array([[[0. , 0. , 0. , ..., 1. , 0. , 0. ],
        [0. , 0. , 0. , ..., 0.3, 0.7, 0. ],
        [0. , 0. , 0. , ..., 0.8, 0.2, 0. ]],

       [[0. , 0. , 0. , ..., 1. , 0. , 0. ],
        [0. , 0. , 0. , ..., 0.3, 0.7, 0. ],
        [0. , 0. , 0. , ..., 0.8, 0.2, 0. ]],

       [[0. , 0. , 0. , ..., 1. , 0. , 0. ],
        [0. , 0. , 0. , ..., 0.3, 0.7, 0. ],
        [0. , 0. , 0. , ..., 0.8, 0.2, 0. ]],

       ...,

       [[0. , 0. , 0. , ..., 1. , 0. , 0. ],
        [0. , 0. , 0. , ..., 0.3, 0.7, 0. ],
        [0. , 0. , 0. , ..., 0.8, 0.2, 0. ]],

       [[0. , 0. , 0. , ..., 1. , 0. , 0. ],
        [0. , 0. , 0. , ..., 0.3, 0.7, 0. ],
        [0. , 0. , 0. , ..., 0.8, 0.2, 0. ]],

       [[0. , 0. , 0. , ..., 1. , 0. , 0. ],
        [0. , 0. , 0. , ..., 0.3, 0.7, 0. ],
        [0. , 0. , 0. , ..., 0.8, 0.2, 0. ]]])

In [28]:
aero_species_list = ['SO4','NO3','Cl','NH4','MSA','ARO1','ARO2','ALK1','OLE1','API1',
                'API2','LIM1','LIM2','CO3','Na','Ca','OIN','OC','BC','H2O']  

In [41]:
aero_species = pd.DataFrame(aero_species_list, columns=['species'], index=np.arange(0,20))

In [45]:
aero_species.iloc[18].species

'BC'